=== AdrianJavier7/Grupo3-LM-Hosting/SoporteRSS.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="title" type="xs:string"/>
    <xs:element name="link" type="xs:string"/>
    <xs:element name="description" type="xs:string"/>
    <xs:element name="section" type="xs:string"/>
    <xs:element name="author" type="xs:string"/>
    <xs:attribute name="version">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="2.0"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>
    <xs:element name="pubDate">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="(0[1-9]|[12][0-9]|3[01])/(0[1-9]|1[0-2])/[0-9]{4}"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="image">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value=".*(.jpeg|.jpg|.png|.bmp|.tiff|.tif|.svg)"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="item">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="title"/>
                <xs:element ref="author"/>
                <xs:element ref="pubDate"/>
                <xs:element ref="link"/>
                <xs:element ref="image"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="channel">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="title"/>
                <xs:element ref="link"/>
                <xs:element ref="description"/>
                <xs:element ref="item" maxOccurs="2"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="rss">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="channel"/>
            </xs:sequence>
            <xs:attribute ref="version"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== AdrianJavier7/Grupo3-LM-Hosting/FeedRSS.xml
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:noNamespaceSchemaLocation="(ruta de SoporteRSS.xsd en tu proyecto)">
    <channel>
        <title>Título</title>
        <link>Enlace</link>
        <description>Descripción</description>
        <item>
            <title>El Athletic descuelga al Girona con su presión adelantada</title>
            <author>JON RIVAS</author>
            <pubDate>19/02/2024</pubDate>
            <link>https://elpais.com/deportes/futbol/2024-02-19/el-athletic-descuelga-al-girona-con-su-presion-adelantada.html</link>
            <image>https://imagenes.elpais.com/resizer/lF3VaY4AGv0Zr2Wc5wDnZJQ-9IA=/1200x0/filters:focal(1985x280:1995x290)/cloudfront-eu-central-1.images.arcpublishing.com/prisa/F6UAPXY6IFEJFJPEJ2PWBOF7IM.jpg</image>
        </item>
        <item>
            <title>Ibai se cae</title>
            <author>Ibai</author>
            <pubDate>18/12/2024</pubDate>
            <link>https://elpais.com/deportes/futbol/2024-02-19/el-athletic-descuelga-al-girona-con-su-presion-adelantada.html</link>
            <image>https://imagenes.elpais.com/resizer/lF3VaY4AGv0Zr2Wc5wDnZJQ-9IA=/1200x0/filters:focal(1985x280:1995x290)/cloudfront-eu-central-1.images.arcpublishing.com/prisa/F6UAPXY6IFEJFJPEJ2PWBOF7IM.jpg</image>
        </item>
    </channel>
</rss>
